service: serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/welcome
          method: get
  fetchsome:
    handler: handler.fetchsome
    events:
      - http:
          path: users/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  requestdata:
    handler: handler.requestdata
    events:
      - http:
          path: requestdata/{id}
          method: post
          request:
            parameters:
              paths:
                id: true
